[MODEL]
name="CoAtNET0"
image_size=224
num_channels=3
num_classes=1000
lengths=[2, 3, 5, 2]
depths=[64, 96, 192, 384, 768]
sizes=[0.25, 0.125, 0.0625, 0.03125]
blocks="CCTT"
mbconv_e=4
mbconv_se=0.25
head_dim=32
mem_eff=true
tfmrel_e=4
qkv_bias=false
fc_e=2
stochastic_rate=0.2